server:
  port: 9001

spring:
  application:
    name: customer-service

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      bootstrap-servers: localhost:9092
      customers-topic-name: customersTopic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/