server:
  port: 9001

management:
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: customer-service

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      bootstrap-servers: localhost:9092
      customers-topic-name: customersTopic

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/